before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/
    binary: inngest
    ldflags:
      - -s -w
      - -X github.com/inngest/inngest/inngest/version.Version={{.Version}}
      - -X github.com/inngest/inngest/inngest/version.Hash={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: inngest
    name: inngest
